### ISSUE TITLE
at each change in glpi db I have to launch dbupdate

### ISSUE THREAD

**Issue by satyan01** [tomolimo/timezones#6] opened 2016-11-16 15:23 UTC
Hello

The plugin is disabled at each change of new table in glpi db,  I have to launch dbupdate to fix it

**Comment by tomolimo** [comment] 2016-11-17 06:54
That's by design to prevent loss of the correct date / time. 
I've planned to improve this but it is not a priority as the db doesn't change every day...

**Comment by AircraftRu** [comment] 2017-03-07 08:29
Confirm the problem. It would be good to fix it.

**Comment by tomolimo** [comment] 2017-03-07 09:08
I've got already a beta version for this, and I plan to deliver it and the next weeks

**Comment by tomolimo** [comment] 2017-05-05 09:10
Fixed by 96a598db79a2da2fdda12cf3d78a7c46f0ddebe7
See latest release: https://github.com/tomolimo/timezones/releases/tag/2.1.2

**Closed as completed by tomolimo** 2017-05-05 09:10 UTC
Labels: enhancement
